import {
  CalendarDays,
  Activity,
  Bell,
  Blocks,
  Bot,
  Crown,
  Database,
  Gavel,
  Gift,
  Hash,
  House,
  KeyRound,
  LayoutDashboard,
  Lock,
  Megaphone,
  MessageSquare,
  Mic,
  Music,
  Palette,
  Plug,
  RefreshCw,
  Sparkles,
  ScrollText,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ticket,
  TrendingUp,
  Trophy,
  Users,
  UserRound,
  UserSearch,
  Volume2,
  Workflow,
  type LucideIcon,
} from 'lucide-react';

/**
 * Erlaubte Navigations- und Modulsymbole.
 *
 * Bewusst als feste Zuordnung statt dynamischem Import: dadurch landet nur ein
 * kleiner Teil der Icon-Bibliothek im Bundle und Module können keine
 * beliebigen Komponenten einschleusen.
 */
const ICONS: Record<string, LucideIcon> = {
  CalendarDays,
  Activity,
  Bell,
  Blocks,
  Bot,
  Crown,
  Database,
  Gavel,
  Gift,
  Hash,
  House,
  KeyRound,
  LayoutDashboard,
  Lock,
  Megaphone,
  MessageSquare,
  Mic,
  Music,
  Palette,
  Plug,
  RefreshCw,
  Sparkles,
  ScrollText,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ticket,
  TrendingUp,
  Trophy,
  Users,
  UserRound,
  UserSearch,
  Volume2,
  Workflow,
};

export function NavIcon({ name, className }: { name: string; className?: string }): React.JSX.Element {
  const Icon = ICONS[name] ?? Blocks;
  return <Icon className={className} aria-hidden="true" />;
}
