import {
  Images,
  Award,
  Star,
  Gem,
  Zap,
  CalendarDays,
  Activity,
  Bell,
  Blocks,
  Bot,
  Clapperboard,
  MessageCircleQuestion,
  Library,
  Radio,
  CalendarClock,
  Dices,
  Gamepad2,
  Crown,
  Database,
  DatabaseBackup,
  Bug,
  Flame,
  HeartHandshake,
  PartyPopper,
  DoorOpen,
  Heart,
  Link2,
  Medal,
  Rocket,
  Swords,
  CalendarCheck,
  Gavel,
  Gift,
  Hash,
  House,
  KeyRound,
  LayoutDashboard,
  Lock,
  Megaphone,
  MessageSquare,
  Mic,
  Music,
  Palette,
  Plug,
  RefreshCw,
  Sparkles,
  ScrollText,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ticket,
  TrendingUp,
  Trophy,
  Users,
  UserRound,
  UserSearch,
  Volume2,
  ArrowRightLeft,
  Workflow,
  type LucideIcon,
} from 'lucide-react';

/**
 * Erlaubte Navigations- und Modulsymbole.
 *
 * Bewusst als feste Zuordnung statt dynamischem Import: dadurch landet nur ein
 * kleiner Teil der Icon-Bibliothek im Bundle und Module können keine
 * beliebigen Komponenten einschleusen.
 *
 * `Award`, `Star`, `Gem` und `Zap` kamen mit den verwaltbaren Auszeichnungen
 * dazu: wer eine anlegt, waehlt ein Symbol, und die Auswahl darf nicht aus
 * vier Pokalen bestehen.
 *
 * Die Namen unten stehen einzeln je Zeile und ohne Kommentar dazwischen -
 * `module-icons.test.ts` liest diesen Block als Text aus.
 */
const ICONS: Record<string, LucideIcon> = {
  Images,
  Award,
  Star,
  Gem,
  Zap,
  CalendarDays,
  Activity,
  Bell,
  Blocks,
  Bot,
  Clapperboard,
  MessageCircleQuestion,
  Library,
  Radio,
  CalendarClock,
  Dices,
  Gamepad2,
  Crown,
  Bug,
  Flame,
  HeartHandshake,
  PartyPopper,
  Database,
  DatabaseBackup,
  Gavel,
  Gift,
  Hash,
  House,
  KeyRound,
  LayoutDashboard,
  Lock,
  Megaphone,
  MessageSquare,
  Mic,
  Music,
  Palette,
  Plug,
  RefreshCw,
  Sparkles,
  ScrollText,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ticket,
  TrendingUp,
  Trophy,
  Medal,
  Swords,
  Heart,
  Rocket,
  Link2,
  DoorOpen,
  CalendarCheck,
  Users,
  UserRound,
  UserSearch,
  Volume2,
  ArrowRightLeft,
  Workflow,
};

export function NavIcon({ name, className }: { name: string; className?: string }): React.JSX.Element {
  const Icon = ICONS[name] ?? Blocks;
  return <Icon className={className} aria-hidden="true" />;
}
